theme: jekyll-theme-architect
# theme: jekyll-theme-minimal
# # Setup
title: Kurtの部屋
# title: 僕の秘密基地
# title: プログラマーの時
# description:      My repos, blogs
# baseurl:      ""
# paginate:     5
# defaults:
#   -
#     scope:
#       path: ""
#     values:
#       layout: "default"
#   -
#     scope:
#       path: ""
#       type: "posts"
#     values:
#       layout: "post"
# exclude: [org/]


# # About/contact
# author:
#   name:       kkatsuyuki
#   url:        https://github.com/kkatsuyuki

plugins:
  - jekyll-sitemap
