#+BEGIN_EXPORT html
---
---
#+END_EXPORT
* My repositories
  - [[https://kkatsuyuki.github.io/myExcelVbaEmacsKey/][myExcelVbaEmacsKey]]

    Excel vba file to use emacs key bindings and some other useful procedures on Excel
  - [[https://kkatsuyuki.github.io/wifi-entries-setup/][wifi-entries-setup]]

    Shell-script program to add the new wifi to =wpa_supplicant.conf=

* Supported repositories
  - [[http://company-mode.github.io/][company-mode]]

    Modular in-buffer completion framework for Emacs

* Procedures for configuring other softwares
  - [[https://kkatsuyuki.github.io/notmuch-conf/][notmuch + emacs + offlineimap]]
    
    Show the configuration procedures of notmuch + emacs + offlineimap

* My gists
  - [[https://gist.github.com/kkatsuyuki/fa930411a86169c3bb1f03337d4af280][eshell-bmk.el]]

    On =eshell=, =bmk= command to =cd= to registered directories is available
  - [[https://gist.github.com/kkatsuyuki/ede09142b817f2e3b97e87ce8bc93736][eshell-completion.el]]

    On =eshell=, complete =systemctl=, =pacman=, =sudo= and =man= which needs subcommands.
  - [[https://gist.github.com/kkatsuyuki/69de02026945d20931897eaf67cd593b][org-auto-export-project.el]]

    If you configure =org-publish-project-alist= of =org-mode= on your =emacs=,
    this export the corresponding =html= file every time you edit and save an =org= file
    in your project directory. I created this seeing [[http://blog.mkoga.net/2012/06/18/auto-publish-org-file/][publish after save on org-mode]].

* My interests
  I'm interested in Emacs, Emacs-lisp, Linux, PIC, assembly. 
  I want to make VBA programs to improve my Excel and Word now.

* Blogs
  # #+HTML: <a href="{{ site.url }}{% post_url 2017-04-14-introduction %}">intro </a>
  #+BEGIN_EXPORT html
  {% for post in paginator.posts %}
  <h3><a href="{{ post.url }}">{{ post.title }}</a></h3>
  <p class="author">
    <span class="date">{{ post.date }}</span>
  </p>
  <div class="content">
    {{ post.excerpt }}
  </div>
  {% endfor %}
  #+END_EXPORT
   
  # derive from jekyll pagination page 
  #+BEGIN_EXPORT html
  {% if paginator.total_pages > 1 %}
  <div class="pagination">
    {% if paginator.previous_page %}
      <a href="{{ paginator.previous_page_path | prepend: site.baseurl | replace: '//', '/' }}">&laquo; Prev</a>
    {% else %}
      <span>&laquo; Prev</span>
    {% endif %}
   
    {% for page in (1..paginator.total_pages) %}
      {% if page == paginator.page %}
        <em>{{ page }}</em>
      {% elsif page == 1 %}
        <a href="{{ paginator.previous_page_path | prepend: site.baseurl | replace: '//', '/' }}">{{ page }}</a>
      {% else %}
        <a href="{{ site.paginate_path | prepend: site.baseurl | replace: '//', '/' | replace: ':num', page }}">{{ page }}</a>
      {% endif %}
    {% endfor %}
   
    {% if paginator.next_page %}
      <a href="{{ paginator.next_page_path | prepend: site.baseurl | replace: '//', '/' }}">Next &raquo;</a>
    {% else %}
      <span>Next &raquo;</span>
    {% endif %}
  </div>
  {% endif %}
  #+END_EXPORT
